"""profile removed chiled parent

Revision ID: 25f829d64503
Revises: f3a371953672
Create Date: 2022-11-20 14:38:03.317644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f829d64503'
down_revision = 'f3a371953672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'user_parent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_parent', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
