"""exception user_id in users

Revision ID: fdb73f5ab466
Revises: 25f829d64503
Create Date: 2022-11-20 15:36:45.815324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb73f5ab466'
down_revision = '25f829d64503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
